#!/bin/bash

TOOLS_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

cd "$TOOLS_ROOT/../" && (coverage run --branch -m nose test || true) && coverage html && cd htmlcov/ && python -m http.server
