name: Docker Image CI

on:
  push:
    branches: [ clean-up ]
  pull_request:
    branches: [ clean-up ]

jobs:

  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
    - run: docker build -t comp0010-system-test . 
    - run: python3 system_test/tests.py
